/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 24-ago.-2021 10:39:54 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Triggers, Sequences for Autonumber Columns */

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_TRIGGERS 
  WHERE TRIGGER_NAME = 'TRG_PEDIDO_K_PEDIDO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP TRIGGER "TRG_PEDIDO_K_PEDIDO"'; 
END IF; 
END;
/

DECLARE 
  C NUMBER; 
BEGIN 
SELECT COUNT(*) INTO C 
FROM USER_SEQUENCES 
  WHERE SEQUENCE_NAME = 'SEQ_PEDIDO_K_PEDIDO'; 
  IF (C > 0) THEN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE "SEQ_PEDIDO_K_PEDIDO"'; 
END IF; 
END;
/


/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CATEGORIA" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CATEGORIA_REP" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CATEGORIA_REPRESENTANTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "CLIENTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "INVENTARIO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "ITEM" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "METODO_DE_PAGO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PAIS" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PEDIDO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "PRODUCTO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REGION" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REPRESENTANTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "REPRESENTANTE_CLIENTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "TIPO_DE_PAGO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "USUARIO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/

/* Create Tables */

CREATE TABLE  "CATEGORIA"
(
	"K_CATEGORIA" NUMBER(10) NOT NULL,	-- codigo de la categoría 
	"N_NOMCATEGORIA" VARCHAR2(50) NOT NULL,	-- nombre de la categoría
	"K_CATEGORIA_PERTENECE" NUMBER(10) NULL	-- codigo de la categoría a la que pertenece
)
;

CREATE TABLE  "CATEGORIA_REP"
(
	"K_CATEGORIA" NUMBER(3) NOT NULL,	-- codigo de la categoría del representante
	"N_NOMCAT" VARCHAR(50) NOT NULL,	-- nombre de la categoría (beginner, junior, senior, master)
	"N_DESCATEGORIA" VARCHAR(50) NOT NULL,	-- descripción de la categoría
	"Q_CALIFICACION_MIN" NUMBER(4,2) NOT NULL,	-- calificación mínima para pertenecer a la categoría
	"Q_VENTAS_MIN" NUMBER(10) NOT NULL,	-- Ventas mínimas para pertenecer a esta categoría
	"V_COMSION" NUMBER(4,2) NOT NULL	-- valor de la comisión para la categoría en cuestión
)
;

CREATE TABLE  "CATEGORIA_REPRESENTANTE"
(
	"K_CATEGORIA_REP" NUMBER(10) NOT NULL,	-- codigo interno de la correspondencia entre categoría y representante
	"K_CATEGORIA" NUMBER(3) NOT NULL,	-- codigo de la categoría a la cual pertenece el representante
	"I_TIPOID_REP" VARCHAR(2) NOT NULL,	-- Tipo de identificacion del representante (CC,CE,PA,NI,OT)
	"Q_IDENTIFICACION_REP" NUMBER(10) NOT NULL,	-- identificación del representante
	"D_INICIO" DATE NOT NULL,	-- fecha cuando se le asigna la categoría a un representante
	"D_TERMINACION" DATE NULL	-- fecha cuando se le termina la categoría a un representante
)
;

CREATE TABLE  "CLIENTE"
(
	"K_TIPOID" VARCHAR(2) NOT NULL,	-- Tipo de identificacion (CC,CE,PA,NI,OT)
	"K_IDENTIFICACION" NUMBER(10) NOT NULL,	-- Identificación del cliente
	"N_CIUDAD" VARCHAR(50) NOT NULL	-- Ciudad del cliente
)
;

CREATE TABLE  "INVENTARIO"
(
	"K_PAIS" NUMBER(3) NOT NULL,	-- codigo del pais
	"K_REGION" NUMBER(2) NOT NULL,	-- codigo de la región
	"K_PRODUCTO" NUMBER(10) NOT NULL,	-- código del producto
	"Q_ENEXISTENCIA" NUMBER(10) NOT NULL,	-- número de productos en existencia
	"V_PRECIO_UNIDAD" NUMBER(11,2) NOT NULL	-- valor del producto para su respectivo país-región
)
;

CREATE TABLE  "ITEM"
(
	"K_ORDEN_FK" NUMBER(10) NOT NULL,	-- codigo de la orden
	"K_ITEM" NUMBER(8) NOT NULL,	-- consecutivo para cada item
	"Q_CANTIDAD" NUMBER(8) NOT NULL,	-- cantidad del item solicitado
	"V_PRECIO" NUMBER(11,2) NOT NULL,	-- precio calculado según la cantidad del item
	"K_PAIS" NUMBER(3) NULL,	-- codigo del pais
	"K_REGION" NUMBER(2) NULL,	-- codigo de la region
	"K_PRODUCTO" NUMBER(10) NULL	-- codigo del producto
)
;

CREATE TABLE  "METODO_DE_PAGO"
(
	"K_PEDIDO" NUMBER(10) NOT NULL,	-- Código del pedido que se va a realizar
	"K_METODO_PAGO" NUMBER(2) NOT NULL,	-- Identificador del método de pago usado por un cliente
	"K_TIPOID_CLI" VARCHAR(2) NOT NULL,	-- Tipo de identificacion (CC,CE,PA,NI,OT) del cliente
	"K_IDENTIFICACION_CLI" NUMBER(10) NOT NULL,	-- Número de identificacion del cliente
	"N_DETALLE_METODO_PAGO" VARCHAR2(50) NOT NULL,	-- Detalle del método de pago
	"K_TIPOPAGO" NUMBER(2) NOT NULL	-- codigo del tipo de pago
)
;

CREATE TABLE  "PAIS"
(
	"K_PAIS" NUMBER(3) NOT NULL,	-- llave primaria del país, se refiere al código numérico del país
	"N_NOMBRE_PAIS" VARCHAR(50) NOT NULL	-- Nombre del país que se referencia
)
;

CREATE TABLE  "PEDIDO"
(
	"K_PEDIDO" NUMBER(10) NOT NULL,	-- identificador del pedido
	"F_PEDIDO" DATE NOT NULL,	-- fecha de la realización del pedido
	"F_LLEGADA" DATE NULL,	-- fecha de la llegada del pedido
	"I_ESTADO" VARCHAR(3) NOT NULL,	-- estado del pedido
	"Q_VALORT" NUMBER(11,2) NOT NULL,	-- valor total del pedido
	"Q_CALIFICACIONPEDIDO" NUMBER(4,2) NULL,	-- calificación del pedido hecha por un cliente
	"K_CLIENTEREP" NUMBER(10) NOT NULL
)
;

CREATE TABLE  "PRODUCTO"
(
	"K_PRODUCTO" NUMBER(10) NOT NULL,	-- Codigo del producto
	"N_NOMPRODUCTO" VARCHAR2(50) NOT NULL,	-- nombre del producto
	"N_DESCPRODUCTO" VARCHAR2(50) NOT NULL,	-- descripción del producto
	"K_CATEGORIA" NUMBER(10) NULL
)
;

CREATE TABLE  "REGION"
(
	"K_PAIS" NUMBER(3) NOT NULL,	-- Código del país que hace hace parte de la Llave primaria de la región.
	"K_REGION" NUMBER(2) NOT NULL,	-- código de la region, hace parte de la llave primaria compuesta
	"N_NOMBRE_REGION" VARCHAR2(50) NOT NULL,	-- Nombre de la región en cuestión
	"I_TIPOID_DIRECTOR" VARCHAR(2) NULL,	-- El tipo de Identificación de la persona que está a cargo de la región (hace parte de la llave foránea del Representante)
	"Q_IDENTIFICACION_DIRECTOR" NUMBER(9) NULL	-- Identificación de la persona que está a cargo de la región (hace parte de la llave foránea del Representante)
)
;

CREATE TABLE  "REPRESENTANTE"
(
	"K_TIPOID" VARCHAR(2) NOT NULL,	-- El tipo de Identificación del representante (hace parte de la llave primaria compuesta del Representante)
	"K_IDENTIFICACION" NUMBER(10) NOT NULL,	-- Identificación del representante (hace parte de la llave primaria compuesta del Representante)
	"I_GENERO" VARCHAR(2) NOT NULL,	-- Genero del representante dado por 2 letras, M, F o NA
	"F_NACIMIENTO" DATE NOT NULL,	-- Fecha de nacimiento del Representante
	"F_CONTRATO" DATE NOT NULL,	-- Fecha de la firma del contrato del Representante
	"K_PAIS" NUMBER(3) NOT NULL,	-- Código del país en la que el representante ejerce su función, hace parte de la Llave primaria de la región.
	"K_REGION" NUMBER(2) NOT NULL,	-- Código de la región en la que el representante ejerce su función
	"Q_CALIFICACION" NUMBER(4,2) NULL,	-- Calificación del representante
	"I_ESTADO" VARCHAR(3) NOT NULL	-- estado del representante
)
;

CREATE TABLE  "REPRESENTANTE_CLIENTE"
(
	"K_CLIENTEREP" NUMBER(10) NOT NULL,	-- Codigo interno de la correspondencia entre cliente y representante
	"F_INICIO_REP" DATE NOT NULL,	-- fecha en la que se agrega el representante a un cliente
	"F_FIN_REP" DATE NULL,	-- fecha en la que se deja de ser representante de un cliente
	"I_TIPOID_CLI" VARCHAR(2) NOT NULL,	-- Tipo de identificacion del cliente (CC,CE,PA,NI,OT)
	"Q_IDENTIFICACION_CLI" NUMBER(10) NOT NULL,	-- identificación del cliente
	"I_TIPOID_REP" VARCHAR(2) NOT NULL,	-- Tipo de identificacion del representante(CC,CE,PA,NI,OT)
	"Q_IDENTIFICACION_REP" NUMBER(10) NOT NULL	-- identificacion del representante
)
;

CREATE TABLE  "TIPO_DE_PAGO"
(
	"K_TIPOPAGO" NUMBER(2) NOT NULL,	-- Consecutivo de cada tipo de pago
	"N_DESCRIPCION" VARCHAR(50) NOT NULL	-- descirpción del tipo de pago
)
;

CREATE TABLE  "USUARIO"
(
	"K_TIPOID" VARCHAR(2) NOT NULL,	-- Tipo de identificacion (CC,CE,PA,NI,OT)
	"K_IDENTIFICACION" NUMBER(10) NOT NULL,	-- Numero de identificacion del cliente
	"N_NOMBRE" VARCHAR2(50) NOT NULL,	-- Nombres del cliente
	"N_APELLIDO" VARCHAR2(50) NOT NULL,	-- Apellidos del clente
	"N_CORREOE" VARCHAR2(50) NOT NULL,	-- Correo electrónico del cliente
	"N_DIRECCION" VARCHAR2(50) NOT NULL,	-- Direccion del cliente
	"Q_TELEFONO" NUMBER(10) NOT NULL,	-- Telefono de contacto del cliente
	"K_TIPOID_USUP" VARCHAR(2) NULL,	-- Tipo de identificacion del usuario que ingresa al usuario
	"K_IDENTIFICACION_USUP" NUMBER(10) NULL,	-- identificacion del usuario que ingresa al usuario
	"N_USUARIO" VARCHAR(20) NOT NULL	-- usuario con el que ingresa el cliente a la aplicación
)
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON COLUMN  "CATEGORIA"."K_CATEGORIA" IS 'codigo de la categoría ';

COMMENT ON COLUMN  "CATEGORIA"."N_NOMCATEGORIA" IS 'nombre de la categoría';

COMMENT ON COLUMN  "CATEGORIA"."K_CATEGORIA_PERTENECE" IS 'codigo de la categoría a la que pertenece';

COMMENT ON TABLE  "CATEGORIA_REP" IS 'Almacenará las posibles categorías de un representante'
;


COMMENT ON COLUMN  "CATEGORIA_REP"."K_CATEGORIA" IS 'codigo de la categoría del representante';

COMMENT ON COLUMN  "CATEGORIA_REP"."N_NOMCAT" IS 'nombre de la categoría (beginner, junior, senior, master)';

COMMENT ON COLUMN  "CATEGORIA_REP"."N_DESCATEGORIA" IS 'descripción de la categoría';

COMMENT ON COLUMN  "CATEGORIA_REP"."Q_CALIFICACION_MIN" IS 'calificación mínima para pertenecer a la categoría';

COMMENT ON COLUMN  "CATEGORIA_REP"."Q_VENTAS_MIN" IS 'Ventas mínimas para pertenecer a esta categoría';

COMMENT ON COLUMN  "CATEGORIA_REP"."V_COMSION" IS 'valor de la comisión para la categoría en cuestión';

COMMENT ON TABLE  "CATEGORIA_REPRESENTANTE" IS 'se almacerará la categoría para un representante'
;


COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."K_CATEGORIA_REP" IS 'codigo interno de la correspondencia entre categoría y representante';

COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."K_CATEGORIA" IS 'codigo de la categoría a la cual pertenece el representante';

COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."I_TIPOID_REP" IS 'Tipo de identificacion del representante (CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."Q_IDENTIFICACION_REP" IS 'identificación del representante';

COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."D_INICIO" IS 'fecha cuando se le asigna la categoría a un representante';

COMMENT ON COLUMN  "CATEGORIA_REPRESENTANTE"."D_TERMINACION" IS 'fecha cuando se le termina la categoría a un representante';

COMMENT ON COLUMN  "CLIENTE"."K_TIPOID" IS 'Tipo de identificacion (CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  "CLIENTE"."K_IDENTIFICACION" IS 'Identificación del cliente';

COMMENT ON COLUMN  "CLIENTE"."N_CIUDAD" IS 'Ciudad del cliente';

COMMENT ON TABLE  "INVENTARIO" IS 'tabla de rompimiento entre region y producto'
;


COMMENT ON COLUMN  "INVENTARIO"."K_PAIS" IS 'codigo del pais';

COMMENT ON COLUMN  "INVENTARIO"."K_REGION" IS 'codigo de la región';

COMMENT ON COLUMN  "INVENTARIO"."K_PRODUCTO" IS 'código del producto';

COMMENT ON COLUMN  "INVENTARIO"."Q_ENEXISTENCIA" IS 'número de productos en existencia';

COMMENT ON COLUMN  "INVENTARIO"."V_PRECIO_UNIDAD" IS 'valor del producto para su respectivo país-región';

COMMENT ON COLUMN  "ITEM"."K_ORDEN_FK" IS 'codigo de la orden';

COMMENT ON COLUMN  "ITEM"."K_ITEM" IS 'consecutivo para cada item';

COMMENT ON COLUMN  "ITEM"."Q_CANTIDAD" IS 'cantidad del item solicitado';

COMMENT ON COLUMN  "ITEM"."V_PRECIO" IS 'precio calculado según la cantidad del item';

COMMENT ON COLUMN  "ITEM"."K_PAIS" IS 'codigo del pais';

COMMENT ON COLUMN  "ITEM"."K_REGION" IS 'codigo de la region';

COMMENT ON COLUMN  "ITEM"."K_PRODUCTO" IS 'codigo del producto';

COMMENT ON TABLE  "METODO_DE_PAGO" IS 'Tabla donde se guardará el metodo de pago utilizado para una factura'
;


COMMENT ON COLUMN  "METODO_DE_PAGO"."K_PEDIDO" IS 'Código del pedido que se va a realizar';

COMMENT ON COLUMN  "METODO_DE_PAGO"."K_METODO_PAGO" IS 'Identificador del método de pago usado por un cliente';

COMMENT ON COLUMN  "METODO_DE_PAGO"."K_TIPOID_CLI" IS 'Tipo de identificacion (CC,CE,PA,NI,OT) del cliente';

COMMENT ON COLUMN  "METODO_DE_PAGO"."K_IDENTIFICACION_CLI" IS 'Número de identificacion del cliente';

COMMENT ON COLUMN  "METODO_DE_PAGO"."N_DETALLE_METODO_PAGO" IS 'Detalle del método de pago';

COMMENT ON COLUMN  "METODO_DE_PAGO"."K_TIPOPAGO" IS 'codigo del tipo de pago';

COMMENT ON TABLE  "PAIS" IS 'Tabla donde se guardarán los países que se requieran'
;


COMMENT ON COLUMN  "PAIS"."K_PAIS" IS 'llave primaria del país, se refiere al código numérico del país';

COMMENT ON COLUMN  "PAIS"."N_NOMBRE_PAIS" IS 'Nombre del país que se referencia';

COMMENT ON TABLE  "PEDIDO" IS 'Se almacenarán los pedidos realizados'
;


COMMENT ON COLUMN  "PEDIDO"."K_PEDIDO" IS 'identificador del pedido';

COMMENT ON COLUMN  "PEDIDO"."F_PEDIDO" IS 'fecha de la realización del pedido';

COMMENT ON COLUMN  "PEDIDO"."F_LLEGADA" IS 'fecha de la llegada del pedido';

COMMENT ON COLUMN  "PEDIDO"."I_ESTADO" IS 'estado del pedido';

COMMENT ON COLUMN  "PEDIDO"."Q_VALORT" IS 'valor total del pedido';

COMMENT ON COLUMN  "PEDIDO"."Q_CALIFICACIONPEDIDO" IS 'calificación del pedido hecha por un cliente';

CREATE SEQUENCE "SEQ_PEDIDO_K_PEDIDO" 
	INCREMENT BY 1 
	START WITH 1 
	NOMAXVALUE 
	MINVALUE  1 
	NOCYCLE 
	NOCACHE 
	NOORDER
;


CREATE OR REPLACE TRIGGER "TRG_PEDIDO_K_PEDIDO" 
	BEFORE INSERT 
	ON "PEDIDO" 
	FOR EACH ROW 
	BEGIN 
		SELECT "SEQ_PEDIDO_K_PEDIDO".NEXTVAL 
		INTO :NEW."K_PEDIDO" 
		FROM DUAL; 
	END;

/


COMMENT ON TABLE  "PRODUCTO" IS 'tabla donde se almacenarán los productos'
;


COMMENT ON COLUMN  "PRODUCTO"."K_PRODUCTO" IS 'Codigo del producto';

COMMENT ON COLUMN  "PRODUCTO"."N_NOMPRODUCTO" IS 'nombre del producto';

COMMENT ON COLUMN  "PRODUCTO"."N_DESCPRODUCTO" IS 'descripción del producto';

COMMENT ON TABLE  "REGION" IS 'Table en donde se guardará la Region de un país específico'
;


COMMENT ON COLUMN  "REGION"."K_PAIS" IS 'Código del país que hace hace parte de la Llave primaria de la región.';

COMMENT ON COLUMN  "REGION"."K_REGION" IS 'código de la region, hace parte de la llave primaria compuesta';

COMMENT ON COLUMN  "REGION"."N_NOMBRE_REGION" IS 'Nombre de la región en cuestión';

COMMENT ON COLUMN  "REGION"."I_TIPOID_DIRECTOR" IS 'El tipo de Identificación de la persona que está a cargo de la región (hace parte de la llave foránea del Representante)';

COMMENT ON COLUMN  "REGION"."Q_IDENTIFICACION_DIRECTOR" IS 'Identificación de la persona que está a cargo de la región (hace parte de la llave foránea del Representante)';

COMMENT ON TABLE  "REPRESENTANTE" IS 'tabla donde se guardaran los representantes'
;


COMMENT ON COLUMN  "REPRESENTANTE"."K_TIPOID" IS 'El tipo de Identificación del representante (hace parte de la llave primaria compuesta del Representante)';

COMMENT ON COLUMN  "REPRESENTANTE"."K_IDENTIFICACION" IS 'Identificación del representante (hace parte de la llave primaria compuesta del Representante)';

COMMENT ON COLUMN  "REPRESENTANTE"."I_GENERO" IS 'Genero del representante dado por 2 letras, M, F o NA';

COMMENT ON COLUMN  "REPRESENTANTE"."F_NACIMIENTO" IS 'Fecha de nacimiento del Representante';

COMMENT ON COLUMN  "REPRESENTANTE"."F_CONTRATO" IS 'Fecha de la firma del contrato del Representante';

COMMENT ON COLUMN  "REPRESENTANTE"."K_PAIS" IS 'Código del país en la que el representante ejerce su función, hace parte de la Llave primaria de la región.';

COMMENT ON COLUMN  "REPRESENTANTE"."K_REGION" IS 'Código de la región en la que el representante ejerce su función';

COMMENT ON COLUMN  "REPRESENTANTE"."Q_CALIFICACION" IS 'Calificación del representante';

COMMENT ON COLUMN  "REPRESENTANTE"."I_ESTADO" IS 'estado del representante';

COMMENT ON TABLE  "REPRESENTANTE_CLIENTE" IS 'tabla de rompimiento entre cliente y representante'
;


COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."K_CLIENTEREP" IS 'Codigo interno de la correspondencia entre cliente y representante';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."F_INICIO_REP" IS 'fecha en la que se agrega el representante a un cliente';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."F_FIN_REP" IS 'fecha en la que se deja de ser representante de un cliente';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."I_TIPOID_CLI" IS 'Tipo de identificacion del cliente (CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."Q_IDENTIFICACION_CLI" IS 'identificación del cliente';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."I_TIPOID_REP" IS 'Tipo de identificacion del representante(CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  "REPRESENTANTE_CLIENTE"."Q_IDENTIFICACION_REP" IS 'identificacion del representante';

COMMENT ON TABLE  "TIPO_DE_PAGO" IS 'Se almacenarán los tipos de pago '
;


COMMENT ON COLUMN  "TIPO_DE_PAGO"."K_TIPOPAGO" IS 'Consecutivo de cada tipo de pago';

COMMENT ON COLUMN  "TIPO_DE_PAGO"."N_DESCRIPCION" IS 'descirpción del tipo de pago';

COMMENT ON TABLE  "USUARIO" IS 'Tabla donde se almacenarán los usuarios'
;


COMMENT ON COLUMN  "USUARIO"."K_TIPOID" IS 'Tipo de identificacion (CC,CE,PA,NI,OT)';

COMMENT ON COLUMN  "USUARIO"."K_IDENTIFICACION" IS 'Numero de identificacion del cliente';

COMMENT ON COLUMN  "USUARIO"."N_NOMBRE" IS 'Nombres del cliente';

COMMENT ON COLUMN  "USUARIO"."N_APELLIDO" IS 'Apellidos del clente';

COMMENT ON COLUMN  "USUARIO"."N_CORREOE" IS 'Correo electrónico del cliente';

COMMENT ON COLUMN  "USUARIO"."N_DIRECCION" IS 'Direccion del cliente';

COMMENT ON COLUMN  "USUARIO"."Q_TELEFONO" IS 'Telefono de contacto del cliente';

COMMENT ON COLUMN  "USUARIO"."K_TIPOID_USUP" IS 'Tipo de identificacion del usuario que ingresa al usuario';

COMMENT ON COLUMN  "USUARIO"."K_IDENTIFICACION_USUP" IS 'identificacion del usuario que ingresa al usuario';

COMMENT ON COLUMN  "USUARIO"."N_USUARIO" IS 'usuario con el que ingresa el cliente a la aplicación';

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "CATEGORIA" 
 ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY ("K_CATEGORIA") 
 USING INDEX
;

CREATE INDEX "IXFK_Categoria_Categoria"   
 ON  "CATEGORIA" ("K_CATEGORIA_PERTENECE") 
;

ALTER TABLE  "CATEGORIA_REP" 
 ADD CONSTRAINT "PK_CATEGORIA_REP"
	PRIMARY KEY ("K_CATEGORIA") 
 USING INDEX
;

ALTER TABLE  "CATEGORIA_REP" 
 ADD CONSTRAINT "CK_Q_VENTAS_MIN" CHECK (Q_VENTAS_MIN>=0)
;

ALTER TABLE  "CATEGORIA_REP" 
 ADD CONSTRAINT "CK_Q_CALIFICACION_MIN" CHECK (Q_CALIFICACION_MIN>=0)
;

ALTER TABLE  "CATEGORIA_REPRESENTANTE" 
 ADD CONSTRAINT "PK_Categoria_Repres_01"
	PRIMARY KEY ("K_CATEGORIA_REP") 
 USING INDEX
;

CREATE INDEX "IXFK_Categoria_Re_Represe02"   
 ON  "CATEGORIA_REPRESENTANTE" ("I_TIPOID_REP","Q_IDENTIFICACION_REP") 
;

CREATE INDEX "IXFK_Categoria_Repr_Categ01"   
 ON  "CATEGORIA_REPRESENTANTE" ("K_CATEGORIA") 
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY ("K_TIPOID","K_IDENTIFICACION") 
 USING INDEX
;

CREATE INDEX "IXFK_CLIENTE_USUARIO2"   
 ON  "CLIENTE" ("K_TIPOID","K_IDENTIFICACION") 
;

ALTER TABLE  "INVENTARIO" 
 ADD CONSTRAINT "PK_Inventario"
	PRIMARY KEY ("K_PAIS","K_REGION","K_PRODUCTO") 
 USING INDEX
;

ALTER TABLE  "INVENTARIO" 
 ADD CONSTRAINT "CK_PRECIO_POSITIVO" CHECK (V_PRECIO_UNIDAD>0)
;

CREATE INDEX "IXFK_Inventario_Producto"   
 ON  "INVENTARIO" ("K_PRODUCTO") 
;

CREATE INDEX "IXFK_Inventario_Region"   
 ON  "INVENTARIO" ("K_PAIS","K_REGION") 
;

ALTER TABLE  "ITEM" 
 ADD CONSTRAINT "PK_Item"
	PRIMARY KEY ("K_ITEM","K_ORDEN_FK") 
 USING INDEX
;

CREATE INDEX "IXFK_Item_Inventario"   
 ON  "ITEM" ("K_PAIS","K_REGION","K_PRODUCTO") 
;

CREATE INDEX "IXFK_Item_Orden"   
 ON  "ITEM" ("K_ORDEN_FK") 
;

ALTER TABLE  "METODO_DE_PAGO" 
 ADD CONSTRAINT "PK_METODO_DE_PAGO"
	PRIMARY KEY ("K_PEDIDO","K_METODO_PAGO") 
 USING INDEX
;

CREATE INDEX "IXFK_METODO_DE_PAGO_CLIENTE"   
 ON  "METODO_DE_PAGO" ("K_TIPOID_CLI","K_IDENTIFICACION_CLI") 
;

CREATE INDEX "IXFK_METODO_DE_PAGO_PEDIDO"   
 ON  "METODO_DE_PAGO" ("K_PEDIDO") 
;

CREATE INDEX "IXFK_METODO_DE_PAGO_TIPO_01"   
 ON  "METODO_DE_PAGO" ("K_TIPOPAGO") 
;

ALTER TABLE  "PAIS" 
 ADD CONSTRAINT "PK_Pais"
	PRIMARY KEY ("K_PAIS") 
 USING INDEX
;

ALTER TABLE  "PAIS" 
 ADD CONSTRAINT "UQ_N_NOMBRE_PAIS" UNIQUE ("N_NOMBRE_PAIS") 
 USING INDEX
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "PK_PEDIDO"
	PRIMARY KEY ("K_PEDIDO") 
 USING INDEX
;

CREATE INDEX "IXFK_PEDIDO_REPRESENTANTE01"   
 ON  "PEDIDO" ("K_CLIENTEREP") 
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "PK_Producto"
	PRIMARY KEY ("K_PRODUCTO") 
 USING INDEX
;

CREATE INDEX "IXFK_PRODUCTO_CATEGOR02"   
 ON  "PRODUCTO" ("K_CATEGORIA") 
;

ALTER TABLE  "REGION" 
 ADD CONSTRAINT "PK_Region"
	PRIMARY KEY ("K_PAIS","K_REGION") 
 USING INDEX
;

ALTER TABLE  "REGION" 
 ADD CONSTRAINT "UQ_N_NOMBRE_REGION" UNIQUE ("N_NOMBRE_REGION") 
 USING INDEX
;

CREATE INDEX "IXFK_Region_Pais"   
 ON  "REGION" ("K_PAIS") 
;

CREATE INDEX "IXFK_Region_Representante"   
 ON  "REGION" ("I_TIPOID_DIRECTOR","Q_IDENTIFICACION_DIRECTOR") 
;

ALTER TABLE  "REPRESENTANTE" 
 ADD CONSTRAINT "PK_Representante"
	PRIMARY KEY ("K_TIPOID","K_IDENTIFICACION") 
 USING INDEX
;

ALTER TABLE  "REPRESENTANTE" 
 ADD CONSTRAINT "CK_Q_POSITIVA" CHECK (Q_CALIFICACION>=0)
;

CREATE INDEX "IXFK_Representante_Region"   
 ON  "REPRESENTANTE" ("K_PAIS","K_REGION") 
;

CREATE INDEX "IXFK_REPRESENTANTE_USUARIO2"   
 ON  "REPRESENTANTE" ("K_TIPOID","K_IDENTIFICACION") 
;

ALTER TABLE  "REPRESENTANTE_CLIENTE" 
 ADD CONSTRAINT "PK_Representant_01"
	PRIMARY KEY ("K_CLIENTEREP") 
 USING INDEX
;

CREATE INDEX "IXFK_Representant_Represe01"   
 ON  "REPRESENTANTE_CLIENTE" ("I_TIPOID_REP","Q_IDENTIFICACION_REP") 
;

CREATE INDEX "IXFK_Representante_Cl_Cli01"   
 ON  "REPRESENTANTE_CLIENTE" ("I_TIPOID_CLI","Q_IDENTIFICACION_CLI") 
;

ALTER TABLE  "TIPO_DE_PAGO" 
 ADD CONSTRAINT "PK_Tipo_de_Pago"
	PRIMARY KEY ("K_TIPOPAGO") 
 USING INDEX
;

ALTER TABLE  "TIPO_DE_PAGO" 
 ADD CONSTRAINT "UQ_N_DESCRIPCION" UNIQUE ("N_DESCRIPCION") 
 USING INDEX
;

ALTER TABLE  "USUARIO" 
 ADD CONSTRAINT "PK_usuario"
	PRIMARY KEY ("K_TIPOID","K_IDENTIFICACION") 
 USING INDEX
;

ALTER TABLE  "USUARIO" 
 ADD CONSTRAINT "UQ_NUSUARIO" UNIQUE ("N_USUARIO") 
 USING INDEX
;

ALTER TABLE  "USUARIO" 
 ADD CONSTRAINT "CK_CLIENTE_TIPOID" CHECK (K_TIPOID IN ('CC','CE','PA','NI','OT'))
;

CREATE INDEX "IXFK_Usuario_Usuario"   
 ON  "USUARIO" ("K_TIPOID_USUP","K_IDENTIFICACION_USUP") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "CATEGORIA" 
 ADD CONSTRAINT "FK_Categoria_Categoria"
	FOREIGN KEY ("K_CATEGORIA_PERTENECE") REFERENCES  "CATEGORIA" ("K_CATEGORIA")
;

ALTER TABLE  "CATEGORIA_REPRESENTANTE" 
 ADD CONSTRAINT "FK_Categoria_Re_Representan_01"
	FOREIGN KEY ("I_TIPOID_REP","Q_IDENTIFICACION_REP") REFERENCES  "REPRESENTANTE" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "CATEGORIA_REPRESENTANTE" 
 ADD CONSTRAINT "FK_Categoria_Repr_Categoria_01"
	FOREIGN KEY ("K_CATEGORIA") REFERENCES  "CATEGORIA_REP" ("K_CATEGORIA")
;

ALTER TABLE  "CLIENTE" 
 ADD CONSTRAINT "FK_Cliente_usuario"
	FOREIGN KEY ("K_TIPOID","K_IDENTIFICACION") REFERENCES  "USUARIO" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "INVENTARIO" 
 ADD CONSTRAINT "FK_Inventario_Producto"
	FOREIGN KEY ("K_PRODUCTO") REFERENCES  "PRODUCTO" ("K_PRODUCTO")
;

ALTER TABLE  "INVENTARIO" 
 ADD CONSTRAINT "FK_Inventario_Region"
	FOREIGN KEY ("K_PAIS","K_REGION") REFERENCES  "REGION" ("K_PAIS","K_REGION")
;

ALTER TABLE  "ITEM" 
 ADD CONSTRAINT "FK_Item_Orden"
	FOREIGN KEY ("K_ORDEN_FK") REFERENCES  "PEDIDO" ("K_PEDIDO")
;

ALTER TABLE  "METODO_DE_PAGO" 
 ADD CONSTRAINT "FK_METODO_DE_PAGO_CLIENTE"
	FOREIGN KEY ("K_TIPOID_CLI","K_IDENTIFICACION_CLI") REFERENCES  "CLIENTE" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "METODO_DE_PAGO" 
 ADD CONSTRAINT "FK_METODO_DE_PAGO_PEDIDO"
	FOREIGN KEY ("K_PEDIDO") REFERENCES  "PEDIDO" ("K_PEDIDO")
;

ALTER TABLE  "METODO_DE_PAGO" 
 ADD CONSTRAINT "FK_METODO_DE_PAGO_TIPO_DE_PAGO"
	FOREIGN KEY ("K_TIPOPAGO") REFERENCES  "TIPO_DE_PAGO" ("K_TIPOPAGO")
;

ALTER TABLE  "PEDIDO" 
 ADD CONSTRAINT "FK_PEDIDO_REPRESENTANTE_CLI_01"
	FOREIGN KEY ("K_CLIENTEREP") REFERENCES  "REPRESENTANTE_CLIENTE" ("K_CLIENTEREP")
;

ALTER TABLE  "PRODUCTO" 
 ADD CONSTRAINT "FK_PRODUCTO_CATEGORIA"
	FOREIGN KEY ("K_CATEGORIA") REFERENCES  "CATEGORIA" ("K_CATEGORIA")
;

ALTER TABLE  "REGION" 
 ADD CONSTRAINT "Director"
	FOREIGN KEY ("I_TIPOID_DIRECTOR","Q_IDENTIFICACION_DIRECTOR") REFERENCES  "REPRESENTANTE" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "REGION" 
 ADD CONSTRAINT "FK_Region_Pais"
	FOREIGN KEY ("K_PAIS") REFERENCES  "PAIS" ("K_PAIS")
;

ALTER TABLE  "REPRESENTANTE" 
 ADD CONSTRAINT "FK_Representante_Region"
	FOREIGN KEY ("K_PAIS","K_REGION") REFERENCES  "REGION" ("K_PAIS","K_REGION")
;

ALTER TABLE  "REPRESENTANTE" 
 ADD CONSTRAINT "FK_Representante_usuario"
	FOREIGN KEY ("K_TIPOID","K_IDENTIFICACION") REFERENCES  "USUARIO" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "REPRESENTANTE_CLIENTE" 
 ADD CONSTRAINT "FK_Representant_Representan_01"
	FOREIGN KEY ("I_TIPOID_REP","Q_IDENTIFICACION_REP") REFERENCES  "REPRESENTANTE" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "REPRESENTANTE_CLIENTE" 
 ADD CONSTRAINT "FK_Representante_Cl_Cliente_01"
	FOREIGN KEY ("I_TIPOID_CLI","Q_IDENTIFICACION_CLI") REFERENCES  "CLIENTE" ("K_TIPOID","K_IDENTIFICACION")
;

ALTER TABLE  "USUARIO" 
 ADD CONSTRAINT "FK_Usuario_Usuario"
	FOREIGN KEY ("K_TIPOID_USUP","K_IDENTIFICACION_USUP") REFERENCES  "USUARIO" ("K_TIPOID","K_IDENTIFICACION")
;
