REM INSERTING into item
SET DEFINE OFF;
--item:
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('1','1','2','20000','1','1','1');
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('2','1','1','6000','1','1','32');
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('3','1','3','1800','1','1','13');
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('4','1','2','900','1','1','13');
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('4','2','1','5000','1','1','9');
Insert into item(K_PEDIDO,K_ITEM, Q_CANTIDAD, V_PRECIO, K_PAIS, K_REGION, K_PRODUCTO ) values ('5','1','1','5000','1','1','9');
