REM INSERTING into Region
SET DEFINE OFF;
Insert into Region(K_PAIS,K_REGION,N_NOMBRE_REGION,K_TIPOID_DIRECTOR,K_IDENTIFICACION_DIRECTOR) values ('1','1','Caribe','','');
Insert into Region(K_PAIS,K_REGION,N_NOMBRE_REGION,K_TIPOID_DIRECTOR,K_IDENTIFICACION_DIRECTOR) values ('1','2','Pacifica','','');
Insert into Region(K_PAIS,K_REGION,N_NOMBRE_REGION,K_TIPOID_DIRECTOR,K_IDENTIFICACION_DIRECTOR) values ('1','3','Andina','','');
Insert into Region(K_PAIS,K_REGION,N_NOMBRE_REGION,K_TIPOID_DIRECTOR,K_IDENTIFICACION_DIRECTOR) values ('1','4','Llanos orientales','','');
Insert into Region(K_PAIS,K_REGION,N_NOMBRE_REGION,K_TIPOID_DIRECTOR,K_IDENTIFICACION_DIRECTOR) values ('1','5','Amazonia','','');