REM INSERTING into categoria_rep_periodo
SET DEFINE OFF;
--Representantes:
Insert into categoria_rep_periodo(K_CATEGORIA_REP,K_CATEGORIA,K_TIPOID_REP,K_IDENTIFICACION_REP,D_INICIO,D_TERMINACION,Q_PROM_CALIFICACION,Q_VENTAS,V_COMISION_TOTAL) values ('1','1','CC', '1111111111',to_date('20/08/21','DD/MM/RR'),NULL,NULL,NULL,NULL);
Insert into categoria_rep_periodo(K_CATEGORIA_REP,K_CATEGORIA,K_TIPOID_REP,K_IDENTIFICACION_REP,D_INICIO,D_TERMINACION,Q_PROM_CALIFICACION,Q_VENTAS,V_COMISION_TOTAL) values ('2','1','CC', '1111111112',to_date('20/08/21','DD/MM/RR'),NULL,NULL,NULL,NULL);
Insert into categoria_rep_periodo(K_CATEGORIA_REP,K_CATEGORIA,K_TIPOID_REP,K_IDENTIFICACION_REP,D_INICIO,D_TERMINACION,Q_PROM_CALIFICACION,Q_VENTAS,V_COMISION_TOTAL) values ('3','4','CC', '1111111113',to_date('20/08/21','DD/MM/RR'),NULL,NULL,NULL,NULL);
